name: UniHub
description: "A new Flutter project."

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png 
  uses-material-design: true 