name: UniHub
description: "A new Flutter project."

flutter_icons:
  android: true
  ios: true
  image_path: assets/light_mode.png

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1 
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.10.0
  firebase_messaging: ^14.0.0
  firebase_analytics: ^10.0.0
  image_picker: ^0.8.7+3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/light_mode.png
    - assets/dark_mode.png
  uses-material-design: true 