name: unihub

description: "A new Flutter project."

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.2
  path: ^1.9.0
  path_provider: ^2.0.15
  firebase_core: ^2.32.0  # Firebase'i başlatmak için
  firebase_auth: ^4.8.0  # Kullanıcı doğrulama için
  cloud_firestore: ^4.10.0  # Firestore veritabanına erişmek için
  firebase_messaging: ^14.0.0
  firebase_analytics: ^10.0.0
  image_picker: ^0.8.7+3  # Görsel seçmek için
  firebase_storage: ^11.0.0  # Fotoğraf yükleme için
  # Diğer gerekli paketler (Firebase'i kullanabilmek için)

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png
  uses-material-design: true
