name: unihub

description: "A new Flutter project."

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  animated_text_kit: ^4.2.1 
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.2
  path: ^1.9.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png 
  uses-material-design: true 