// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ir0PgQBh3fqxkJtWeJd43-5WhOwr94Q',
    appId: '1:381691973407:web:a254d25fd9663e197bea2a',
    messagingSenderId: '381691973407',
    projectId: 'unihub-290c5',
    authDomain: 'unihub-290c5.firebaseapp.com',
    storageBucket: 'unihub-290c5.firebasestorage.app',
    measurementId: 'G-G21651ZWC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wi2u4ZYi-X9nNt96S-CGUqwr4QQsn60',
    appId: '1:381691973407:android:5a471dfa44949a5b7bea2a',
    messagingSenderId: '381691973407',
    projectId: 'unihub-290c5',
    storageBucket: 'unihub-290c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBA2ZtPBQZSFr3qzLaUvHmSvjxT9-_3z4',
    appId: '1:381691973407:ios:ffaf53fa5194a4487bea2a',
    messagingSenderId: '381691973407',
    projectId: 'unihub-290c5',
    storageBucket: 'unihub-290c5.firebasestorage.app',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBA2ZtPBQZSFr3qzLaUvHmSvjxT9-_3z4',
    appId: '1:381691973407:ios:ffaf53fa5194a4487bea2a',
    messagingSenderId: '381691973407',
    projectId: 'unihub-290c5',
    storageBucket: 'unihub-290c5.firebasestorage.app',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8ir0PgQBh3fqxkJtWeJd43-5WhOwr94Q',
    appId: '1:381691973407:web:53837905aaa295d87bea2a',
    messagingSenderId: '381691973407',
    projectId: 'unihub-290c5',
    authDomain: 'unihub-290c5.firebaseapp.com',
    storageBucket: 'unihub-290c5.firebasestorage.app',
    measurementId: 'G-PDCQGBQV94',
  );
}
